[colors]
background = "#1e222aFF"
text_primary = "#d1d1c7FF"
text_muted = "#8e959eFF"
accent_primary = "#e6b450FF"
accent_secondary = "#aad94cFF"
warning = "#39bae6FF"
error = "#d95757FF"
insert_hint = "#39bae680"
backdrop = "#1e222aFF"

[colors.border]
focused = "#e6b450FF"
unfocused = "#1e222aFF"
outer = "#0b0e14FF"

[colors.overview]
background_tint = "#0b0e1488"
badge = "#e6b450FF"
workspace_background = "#0b0e14FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#39bae6FF"
border_color_unfocused = "#0a4c62FF"
